spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/appingreso?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl        
    properties:
      hibernate: 
        dialeg: org.hibernate.dialect.MySQL5Dialect
      